### ISSUE TITLE
Method not found: int SQLitePCL.raw.sqlite3_bind_blob

### ISSUE THREAD

**Issue by Senso4sLab** [praeclarum/sqlite-net#1074]
The SQLite works just fine on Android phones. When I tried to upload a mobile application on an iOS phone I got the exception shown below. When the object was trying to be inserted or updated in the database this exception occurred. Based on my knowledge this exception appears when I updated Xamarin.iOS to version 15.0. I will appreciate it if someone helps me to solve the problem.

{System.MissingMethodException: Method not found: int SQLitePCL.raw.sqlite3_bind_blob(SQLitePCL.sqlite3_stmt,int,System.ReadOnlySpan`1<byte>)
  at SQLite.SQLiteCommand.BindParameter (SQLitePCL.sqlite3_stmt stmt, System.Int32 index, System.Object value, System.Boolean storeDateTimeAsTicks, System.String dateTimeStringFormat, System.Boolean storeTimeSpanAsTicks) <0x10ac37dc0 + 0x002e6> in <01c96d411fe34bd5940c99a56515582b>:0 
  at SQLite.PreparedSqlLiteInsertCommand.ExecuteNonQuery (System.Object[] source) <0x10c064d40 + 0x000fc> in <01c96d411fe34bd5940c99a56515582b>:0 
  at SQLite.SQLiteConnection.Insert (System.Object obj, System.String extra, System.Type objType) <0x10c060628 + 0x00178> in <01c96d411fe34bd5940c99a56515582b>:0 
  at SQLite.SQLiteConnection.Insert (System.Object obj) <0x10c05fbd0 + 0x00020> in <01c96d411fe34bd5940c99a56515582b>:0 
  at SQLite.SQLiteAsyncConnection+<>c__DisplayClass50_0.<InsertAsync>b__0 (SQLite.SQLiteConnectionWithLock conn) <0x10c05f9d8 + 0x0000e> in <01c96d411fe34bd5940c99a56515582b>:0 
  at (wrapper delegate-invoke) System.Func`2[SQLite.SQLiteConnectionWithLock,System.Int32].invoke_TResult_T(SQLite.SQLiteConnectionWithLock)
  at SQLite.SQLiteAsyncConnection+<>c__DisplayClass33_0`1[T].<WriteAsync>b__0 () <0x10c05f5d8 + 0x00032> in <01c96d411fe34bd5940c99a56515582b>:0 
  at (wrapper delegate-invoke) System.Func`1[System.Int32].invoke_TResult()
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
--- End of stack trace from previous location where exception was thrown ---

**Comment by BlueRaja** [comment]
They claimed this was fixed in VS 2022 17.0.3, but it appears to still be happening in VS 2022 17.0.5.

**Comment by catapedamania** [comment]
> They claimed this was fixed in VS 2022 17.0.3, but it appears to still be happening in VS 2022 17.0.5. Unfortunately there's no way to downgrade...

Also happening in VS 2022 17.1.0

**Comment by kkppstudios** [comment]
Still happening on 17.1.2. Anyone have any solution or work-around for this?

**Comment by nemekzg** [comment]
> Still happening on 17.1.2. Anyone have any solution or work-around for this?

You might be able to work around the issue if you force your project to use System.Memory, version 4.5.2. I've added it with NuGet to my project and the problem's gone.

**Comment by hugomr89** [comment]
I had the same error on my App, fiddling around with my models I found out it had something to do with the byte array (byte[]) data type, I modified my project to store the information on strings instead (not ideal, but it works), I prefered this insead of the System.Memory workaround
