### ISSUE TITLE
LINQ where datetime [System.NotSupportedException] = {"Member access failed to compile expression"}

### ISSUE THREAD

**Issue by fbregeon-ir** [praeclarum/sqlite-net#350]
Hello, 
when you do a linq on table with where clause and condition on datetime field.
We get this error :
[System.NotSupportedException] = {"Member access failed to compile expression"}

Sample of code to reproduce here :

https://onedrive.live.com/redir?resid=8E2FA15AB7D1C5D8!21708&authkey=!AIdaJ5f4PUzu8c8&ithint=file%2czip

Thanks for your reply.

**Comment by roryok** [comment]
I have the same issue. I've also tried selecting with a SQL query and this also fails

**Comment by nurchi** [comment]
In your code: `SQLite.SQLiteConnection cn = new SQLite.SQLiteConnection(@"c:\temp\test.db",false);`

Try changing `false` to `true`

I never had an issue when using binary form for `DateTime`.

**Comment by jsbeckr** [comment]
I have to confirm this issue at least when you use a normal LINQ query (with storeDateTimeAsTicks = true). Have to try the SQL version, I hope that works at least.

**Comment by bartdkmediahuis** [comment]
Anyone looking into a solution for this problem ?
When storing nullable dateTime this is throwing same exception.

**Comment by taurenshaman** [comment]
A simple solution:
Not use DateTime? type, Use DateTime dierctly.
If you wanna express a null value, set it to DateTime.MinValue instead.
^_^

**Comment by praeclarum** [comment]
Looks like we need a test case for this. Sorry for the trouble!

**Comment by bartdkmediahuis** [comment]
@praeclarum : A test case is rather easy to set up.
Create a nullable DateTime column, write a where clause on this field and the exception is thrown.

`  at SQLite.TableQuery`1[T].CompileExpr (System.Linq.Expressions.Expression expr, System.Collections.Generic.List`1[T] queryArgs) [0x00764] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:2907 
  at SQLite.TableQuery`1[T].CompileExpr (System.Linq.Expressions.Expression expr, System.Collections.Generic.List`1[T] queryArgs) [0x0009d] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:2811 
  at SQLite.TableQuery`1[T].GenerateCommand (System.String selectionList) [0x00068] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:2767 
  at SQLite.TableQuery`1[T].GetEnumerator () [0x0000b] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLite.cs:3043 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:98 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at MH.MobileApps.Data.Repository.PublicationDownloadInfoRepository+<>c__DisplayClass35_0.<RemoveExpiredPublications>b__0 (SQLite.SQLiteConnection connection) [0x00001] in /Users/bartdk/vsts/mobile-apps/projects/Shared/Data/Repository/PublicationDownloadInfoWriteRepository.cs:371 
  at MH.MobileApps.Data.Database+<>c__DisplayClass10_0.<RunInTransaction>b__0 (SQLite.SQLiteConnection trans) [0x00001] in /Users/bartdk/vsts/mobile-apps/projects/Shared/Data/Database.cs:71 
  at SQLite.SQLiteAsyncConnection+<RunInTransactionAsync>c__AnonStoreyD.<>m__0 () [0x00037] in /Users/fak/Dropbox/Projects/sqlite-net/src/SQLiteAsync.cs:282 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2879 
  at System.Threading.Tasks.Task.Execute () [0x00010] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2502 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at MH.MobileApps.Data.Repository.PublicationDownloadInfoRepository+<RemoveExpiredPublications>d__35.MoveNext () [0x00066] in /Users/bartdk/vsts/mobile-apps/projects/Shared/Data/Repository/PublicationDownloadInfoWriteRepository.cs:369 `

**Comment by ptofanelli** [comment]
> In your code: `SQLite.SQLiteConnection cn = new SQLite.SQLiteConnection(@"c:\temp\test.db",false);`
> 
> Try changing `false` to `true`
> 
> I never had an issue when using binary form for `DateTime`.

Thank you. Worked for me.
My case: I had a PCL Xamarin Forms App that I had to change to .Net Standard 2.0 and this problem came up.

**Comment by banarualexandru** [comment]
I had the same problem. 
After some investigations, I faced next conclusions:

1. When use **HasValue** and **Value** properties from nullable datetime entity, it crashes
`IQUERYABLE.Where(s => s.CreatedAt.HasValue && s.CreatedAt.Value > context.LastSyncDate).ToList();`
2. When avoid using **HasValue** and **Value**, it works as expected.
`IQUERYABLE.Where(s => s.CreatedAt != null && s.CreatedAt > context.LastSyncDate).ToList();`

This approach could be useful for those who need to store datetime as string.

**Comment by praeclarum** [comment]
This was fixed in 1.6.

**Comment by NipunKalra** [comment]
Hi @praeclarum I am still getting this exception. I am using sqlite-net-sqlcipher (1.6.258-beta) with net std 2.0.3. 
I have just added a new column in a table and then in one of my old query I have updated the predicate to get the column. With new column is added to existing records the value will be null and  I am getting the exception. any suggestions, please thanks.
